### ISSUE TITLE
UTF-8 support.

### ISSUE THREAD

**Issue by flexd** [ajford/flask-sendmail#6]
I am having trouble sending mails in utf-8. 

Do you know what would be required to send utf-8 emails? Is there anything missing? :-)

**Comment by ajford** [comment]
Check out the latest devel version (0.2) here on github. It has the ability to set the charset for the body, thanks to @mondone, who recently submitted a PR.

**Comment by flexd** [comment]
That is great for flask-sendmail users :-)

I actually ended up using this instead, a fairly easy way of sending an email (at least internally here on our network).

``` python
def sendemail(subject, message, emails):
    from_ = config.get('email', 'from')
    host = config.get('email', 'host')

    msg = MIMEMultipart('alternative')
    msg['Subject'] = subject.decode('utf-8')
    msg['From'] = from_.decode('utf-8')

    body = MIMEText(message.replace('\n', '<br />').strip().decode('utf-8'), 'html', 'utf-8')
    msg.attach(body)

    try:
        s = smtplib.SMTP()
        s.connect(host = host)
        s.sendmail(from_, emails, msg.as_string())
        s.close()
        print('Email sent to: %s' % emails)
    except:
        print("Error sending email to: %s" % emails)
        sys.exc_info()[0]
        pass

```

**Comment by ajford** [comment]
SMTP is fantastic when you have the ability to use it. It is my preferred method of email dispatch for web-apps, but while developing some apps for the Physics Dept. at the University of Texas at Brownsville, I was unable to use SMTP to reach the department mail server due to firewall issues that we were unable to resolve with IT. To work around that, I leveraged the "blessed" sendmail system they agreed to install, and created Flask-Sendmail to share my work with others.
